config/routes.rb
FramgiaJobs::Application.routes.draw do
  devise_for :admins
  root to: "top#index"
  namespace :admin do
    root to: "entries#index"
    resources :entries, except: [:new, :create]
  end
  resources :entries, only: [:new, :create]
  resource :recruits, only: [:show]
  get "/entries/finish", to: "entries#finish"
  get "*a", to: "application#render_404"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  PERMITTED_PARAMS = [:name, :email, :github_id, :m_job_id, :self_pr,
    :other_information, :cv, :cv_cache, :remove_cv]
  validates :name, :email, :m_job_id, :self_pr, :cv, presence: true
  belongs_to :m_job, class_name: M::Job.name
  mount_uploader :cv, CvUploader
end

app/models/m.rb
module M
  def self.table_name_prefix
    'm_'
  end
end

app/models/m/job.rb
class M::Job < ActiveRecord::Base
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_layout"

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for resource
    admin_root_path
  end

  def render_404
    redirect_to root_path
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :build_object

  def new
  end

  def create
    if @entry.save
      UserMailer.send_email(@entry).deliver
      UserMailer.thank_mail(@entry).deliver
      redirect_to entries_finish_path
    else
      render :new
    end
  end

  def finish
  end

  private

  def build_object
    @entry = Entry.new
    @entry.attributes = entry_params if params[:entry]
  end

  def entry_params
    params.require(:entry).permit Entry::PERMITTED_PARAMS
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  def show
    render "recruits/_#{params[:job]}"
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/entries/index.html.erb
<table>
  <tr>
    <th>STT</th>
    <th>Name</th>
    <th>Job</th>
  </tr>
<% @entries.each_with_index do |entry, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= link_to entry.name, admin_entry_path(entry) %></td>
    <td><%= entry.try(:m_job).try(:name) %></td>
  </tr>
<% end %>
</table>

app/views/admin/entries/show.html.erb
<table>
  <tr>
    <td>Name</td>
    <td><%= @entry.name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @entry.email %></td>
  </tr>
  <tr>
    <td>Job</td>
    <td><%= @entry.m_job.try(:name) %></td>
  </tr>
  <tr>
    <td>Github</td>
    <td><%= @entry.github_id %></td>
  </tr>
  <tr>
    <td>Self PR</td>
    <td><%= @entry.self_pr %></td>
  </tr>
  <tr>
    <td>Other information</td>
    <td><%= @entry.other_information %></td>
  </tr>
  <tr>
    <td>CV</td>
    <td><%= link_to "CV", @entry.cv_url %></td>
  </tr>
</table>
<%= link_to "Back", admin_root_path %>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" >
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Framgia Việt Nam Tuyển Dụng | Công ty IT Nhật Bản tại Hà Nội</title>
  <meta property="og:image" content="http://recruit.framgia.vn<%= image_path 'ogp_framgia.png' %>"/>
  <meta name="description" content="Làm việc tại Hà Nội, onsite Nhật Bản, Framgia tuyển dụng các vị trí lập trình viên Android, PHP, iOS, BrSE, QA/Tester...">
  <meta name="keywords" content="tuyển dụng developer, tuyển lập trình viên, kỹ sư IT">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <style>
  .new_position {
  text-align:center;
  font-family:Helvetica,sans-serif;
  padding-top:20px;
  -webkit-animation-fill-mode:both;
  -moz-animation-fill-mode:both;
  -o-animation-fill-mode:both;
  animation-fill-mode:both;

  -webkit-animation:blink 1s infinite;
  -moz-animation:blink 1s infinite;
  -o-animation:blink 1s infinite;
  animation:blink 1s infinite;
}

@-webkit-keyframes blink {
  0%,50%,100% {
    opacity:1;
  }

  25%,75% {
    opacity:0;
  }
}

@keyframes blink {
  0%,50%,100% {
    opacity:1;
  }

  25%,75% {
    opacity:0;
  }
}
  </style>
  <%= csrf_meta_tags %>
  <link rel="canonical" href="jobs.html"/>
  <link rel="shortcut icon" href="../assets.Framgia.com/production/assets/favicon-36a0e5df021b247a23c073e922ee76d2.png">
  <link rel="apple-touch-icon" href="../assets.Framgia.com/production/assets/apple-touch-icon-38fe2e51027979e8c7034635f5dabeca.png" content="Framgia" />
  <meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0" />
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46995268-2', 'framgia.vn');
    ga('send', 'pageview');
  </script>
  <%= yield(:facebook_conversion) if content_for?(:facebook_conversion) %>
</head>
<div id="header" class="hidden-phone">
  <div class="header-inner">
    <h1 id="img-logo-box">
    <a href="/"><%= image_tag 'logo_framgia.png', id: "img-logo-box" %></a>
    </h1>
    <div id="gnav-box">
      <div class="header-btn-box">
        <a href="<%= new_entry_path %>" class="btn btn-primary btn-alt ga-top-linkto-signup">Gửi CV</a>
      </div>
      <div class="header-menu-box hidden-phone">
        <a href="<%= root_path %>#header-image-box" class="scroll">Lời Ngỏ</a>
        <a href="<%= root_path %>#jobs-culture-container" class="scroll">Văn Hóa</a>
        <a href="<%= root_path %>#jobs-team-container" class="scroll">Team</a>
        <a href="<%= root_path %>#jobs-positions-container" class="scroll">Công Việc</a>
      </div>
    </div>
  </div>
</div>
<!-- MENU MOBILE -->
<div class="navbar navbar-fixed-top visible-phone" id="navbar-mobile">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-navbar" DATA-TOGGLE="collapse" DATA-TARGET=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a href="index.html" class="logo-box-small"></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="jobs.html#header-image-box" class="scroll">Lời Ngỏ</a></li>
          <li><a href="jobs.html#jobs-culture-container" class="scroll">Văn Hóa</a></li>
          <li><a href="jobs.html#jobs-team-container" class="scroll">Team</a></li>
          <li><a href="jobs.html#jobs-positions-container" class="scroll">Công Việc</a></li>
        </ul>
      </div>
      <!-- /.nav-collapse --> 
    </div>
    <!-- /.container --> 
  </div>
  <!-- /.navbar-inner --> 
</div>
<body DATA-SPY="scroll" DATA-TARGET="#navbar">
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '432816793580731',
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<%= yield %>
<div id="footer">
  <div id="footer-inner"> 
    <hr style="margin-top:0;"/>
    <p class="pagination-centered">Framgia Viet Nam Co.,Ltd<br>
13F, KeangNam LandMark 72 Building, E6 Pham Hung, Tu Liem, HN</p>
    <p class="pagination-centered">Tel: 04 3795 5417</p>
    <p class="pagination-centered">© 2014 Framgia, Inc. All rights reserved.</p>
  </div>
</div>
<%= yield(:google_js) if content_for?(:google_js) %>
</body>
<meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->
</html>

app/views/recruits/_admin-staff.html.erb
<div id="page-jobs-apply">
  <div class="container middle">
    <a href="/" class="jobs-back-link">←Quay lại</a>
    <hr class="margin-small-white" />
    <h3>Administration Staff</h3>
    <h5>Mô tả công việc</h5>
    <ul>
      <li>Book phòng họp</li>
      <li>Sắp xếp lịch họp</li>
      <li>Mua văn phòng phẩm, vật dụng (nước, đồ uống) cho văn phòng</li>
      <li>Lưu trữ hồ sơ, đầu mối công văn, giấy tờ ra ngoài công ty, tiếp nhận hồ sơ gửi tới công ty.</li>
      <li>In ấn, photo tài liệu khi cần thiết</li>
      <li>Hỗ trợ các bạn sinh viên thực tập ngồi tại văn phòng</li>
      <li>Trực điện thoại</li>
      <li>Phối hợp quản lý tài sản</li>
      <li>Thực hiện các công việc hành chính được yêu cầu khác</li>
    </ul>
    <h5>Yêu cầu công việc</h5>
    <ul>
      <li>Tốt nghiệp đại học</li>
      <li>Không yêu cầu kinh nghiệm</li>
      <li>Cởi mở, trung thực, tận tình với công việc</li>
      <li>Có kỹ năng giao tiếp tốt, chịu được áp lực cao</li>
      <li>Sử dụng tốt tiếng Anh</li>
      <li>Lương thoả thuận</li>
    </ul>
    <h5>Chế độ đãi ngộ</h5>
    <ul>
      <li>Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo luật Bảo hiểm</li>
      <li>Xét tăng lương theo năng lực và kết quả công việc: 1 lần/năm.</li>
      <li>Điều chỉnh lương theo trượt giá thị trường: 1 lần/năm.</li>
      <li>Lương tháng 13</li>
      <li>Được hưởng trợ cấp ăn trưa 840.000VND/1 tháng.</li>
      <li>Trợ cấp đi lại tối thiểu 210.000VND/1 tháng, tối đa 630.000 VND/1 tháng (tùy thuộc vào khoảng cách từ nhà đến Công ty)</li>
      <li>Trợ cấp Beauty Care 300.000VND/Tháng với nhân viên nữ ký hợp đồng chính thức</li>
      <li>Trợ cấp thai sản (Hưởng thêm 3 tháng lương của nhân viên ngoài lương do Bảo hiểm và nhà nước chi trả)</li>
      <li>Trợ cấp tiếng Nhật, tiếng Anh, và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...)</li>
      <li>Hỗ trợ phí tham gia Hội thảo ngoài Công ty 100.000 VND/ ngày</li>
      <li>Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, các CLB Game, CLB dạy và học </li>tiếng Nhật, tham gia các bữa tiệc, hoạt động ngoại khóa của công ty ...</li>
      <li>Du lịch hàng năm</li>
      <li>Khám sức khỏe 1 năm/1 lần</li>
    </ul>
    <h5>Lương & hợp đồng làm việc:</h5>
    <ul>
      <li>Mức lương: 8.000.000 – 11.000.000 VNĐ.</li>
      <li>Thử việc 2 tháng.</li>
      <li>Thời gian làm việc: 5 ngày/tuần (từ thứ 2 đến thứ 6)</li>
    </ul>
    <div class="modal-footer"><a class="btn btn-alt btn-primary" href="<%= new_entry_path("entry[m_job_id]" => 2) %>">Apply Now</a></div>
  </div>
</div>

app/views/recruits/_biz-design-coder.html.erb
<div id="page-jobs-apply">
  <div class="container middle">
    <a href="/" class="jobs-back-link">←Quay lại</a>
    <hr class="margin-small-white" />
    <h3>Design and Coder</h3>
    <h5>Mô tả công việc</h5>
    <p>Công ty Framgia đang tuyển designer kiêm coder cho dự án <a href="https://viblo.asia">Viblo.</a></p>
    <p>Viblo là sản phẩm của chính Framgia tạo ra với phương châm ""nói tiếng nước nào, học lập trình bằng tiếng nước đó"".</p>
    <p><a href="https://viblo.asia">https://viblo.asia</a></p>
    <p>Đối với <a href="https://viblo.asia">Viblo.</a>, chúng tôi kì vọng đây sẽ là nơi mà người châu Á có thể học mọi thứ về lập trình bằng chính tiếng bản ngữ của họ, đồng thời là bước đầu tiên trong quá trình đưa những nhân tài lập trình đang ""ẩn dật"" của châu Á đến với toàn thế giới. Kế hoạch của chúng tôi là tạo ra môi trường sap cho những nhân tài đó có thể tiếp xúc với các cơ hội nhiều nhất có thể.</p>
    <p><a href="https://viblo.asia">Viblo</a> đang trong quá trình phát triển và có rất nhiều việc cần làm. Nếu bạn cảm thấy hứng thú với mục tiêu của chúng tôi, hãy ứng tuyển vào vị trí designer kiêm coder cho <a href="https://viblo.asia">Viblo.</a></p>
    <h5>Yêu cầu công việc</h5>
    <ul>
      <li>Yêu cầu về design :
        <ul>
          <li>Có 3 năm kinh nghiệm trở lên đối với việc design cho Web hoặc ứng dụng smartphone (cần gửi kèm portofolio)</li>
          <li>Có kinh nghiệm làm nhóm cùng với developer</li>
          <li>Có kinh nghiệm sử dụng Photoshop/Illustrator</li>
          <li>Có kinh nghiệm cải thiện UI/UX dựa vào các số liệu thu được bằng Google Analytics hoặc các công cụ lấy log khác</li>
          <li>Có khả năng điều chỉnh linh hoạt design dựa trên số liệu thu được hoặc dựa trên cơ sở tối ưu hóa trải nghiệm người dùng</li>
        </ul>
      </li>
      <li>Yêu cầu về coding :
        <ul>
          <li>Có 3 năm kinh nghiệm trở lên đối với HTML5/CSS3/JavaScrip hoặc kinh nghiệm tương đương (cần gửi kèm portofolio)</li>
          <li>Có kinh nghiệm điều chỉnh tối ưu hóa responsive đối với Website</li>
          <li>Có kinh nghiệm làm nhóm cùng với developer</li>
          <li>Có kinh nghiệm sử dụng Photoshop/Illustrator</li>
          <li>Có kinh nghiệm cải thiện UI/UX dựa vào các số liệu thu được bằng Google Analytics hoặc các công cụ lấy log khác</li>
          <li>Có khả năng báo cáo, liên lạc, bàn bạc một cách tỉ mỉ và chi tiết</li>
        </ul>
      </li>
    </ul>
    <h5>Địa điểm làm việc</h5>
    <ul>
      <li>Hà Nội hoặc Thành phố Hồ Chí Minh</li>
      <li>Trong trường hợp ứng viên có nguyện vọng làm việc tại Thành phố Hồ chí Minh, yêu cầu 3 tháng đầu đi làm tại Hà Nội, rồi sau đó mới chuyển vào Thành phố Hồ Chí Minh. Công ty có dự định thành lập chi nhánh ở Quận 1 nhưng chưa rõ địa điểm và thời gian cụ thể, công ty có trả phí nhà ở và vé máy bay.</li>
    </ul>
    <h5>Chế độ đãi ngộ</h5>
    <ul>
      <li>Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo luật Bảo hiểm</li>
      <li>Xét tăng lương theo năng lực và kết quả công việc: 1 lần/năm.</li>
      <li>Điều chỉnh lương theo trượt giá thị trường: 1 lần/năm.</li>
      <li>Lương tháng 13</li>
      <li>Được hưởng trợ cấp ăn trưa 840.000VND/1 tháng.</li>
      <li>Trợ cấp đi lại tối thiểu 210.000VND/1 tháng, tối đa 630.000 VND/1 tháng (tùy thuộc vào khoảng cách từ nhà đến Công ty)</li>
      <li>Trợ cấp Beauty Care 300.000VND/Tháng với nhân viên nữ ký hợp đồng chính thức</li>
      <li>Trợ cấp thai sản (Hưởng thêm 3 tháng lương của nhân viên ngoài lương do Bảo hiểm và nhà nước chi trả)</li>
      <li>Trợ cấp tiếng Nhật, tiếng Anh, và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...)</li>
      <li>Hỗ trợ phí tham gia Hội thảo ngoài Công ty 100.000 VND/ ngày</li>
      <li>Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, các CLB Game, CLB dạy và học </li>tiếng Nhật, tham gia các bữa tiệc, hoạt động ngoại khóa của công ty ...</li>
      <li>Du lịch hàng năm</li>
      <li>Khám sức khỏe 1 năm/1 lần</li>
    </ul>
    <h5>Lương và Hợp đồng làm việc</h5>
    <ul>
      <li>Mức lương: $600 – $1500</li>
      <li>Thử việc 2 tháng</li>
      <li>Sau thử việc, ký hợp đồng chính thức, lương thỏa thuận theo kết quả thử việc</li>
      <li>Ngày nghỉ :
        <ul>
          <li>Nghỉ thứ 7, Chủ Nhật và các ngày lễ do công ty qui định</li>
          <li>Thời gian học tập nghiên cứu : 16 giờ / tháng</li>
        </ul>
      </li>
    </ul>
    <h5>Yêu cầu khác</h5>
    <ul>
      <li>CV tiếng Anh, ghi rõ về những việc đã từng làm, kinh nghiệm và quá trình học tập của bản thân</li>
      <li>Gửi kèm sản phẩm demo hoặc source code do bản thân tự làm (nếu có)</li>
      <li>Cần ghi rõ với vai trò là Designer & Coder thì nhiệm vụ cụ thể và công việc của bản thân trong các dự án đã từng làm là gì</li>
      <li>Sau khi kiểm tra CV đạt yêu cầu sẽ liên lạc để hẹn lịch phỏng vấn</li>
    </ul>
    <div class="modal-footer"><a class="btn btn-alt btn-primary" href="<%= new_entry_path("entry[m_job_id]" => 7) %>">Apply Now</a></div>
  </div>
</div>

app/views/recruits/_biz-english.html.erb
<div id="page-jobs-apply">
  <div class="container middle">
    <a href="/" class="jobs-back-link">←Quay lại</a>
    <hr class="margin-small-white" />
    <h3>Japanese & English Communicator</h3>
    <h5>Mô tả công việc</h5>
    <p>Cần tuyển người phát triển dịch vụ mới dành cho thị trường Việt Nam. Dịch vụ được phát triển trên nền tảng Web và smartphone bằng các ngôn ngữ PHP (Laravel Framework), Java (Android), Swift (iOS).</p>
    <p>Dự án mang lại niềm vui bằng việc phát triển sản phầm từ con số 0. Tuy nhiên dự án cũng sẽ khó nhiều thử thách ldo với mục tiêu sản phẩm phải được nhiều người đón nhận, trong quá trình làm sẽ có nhiều thay đổi xuất phát từ thông số thực tế như số lượng truy cập hay phản ứng của người dùng. Chúng tôi cần người có thể sẵn sàng đương đầu và lấy những khó khăn đó làm bàn đạp để ngày một trưởng thành.</p>
    <h5>Yêu cầu công việc</h5>
    <ul>
      <li>Có trình độ cao về tiếng Anh (kinh nghiệm biên phiên dịch 2 năm trở lên) và khả năng sử dụng tiếng Anh trong công việc (khả năng đối thoại bằng tiếng Anh)</li>
      <li>Nữ</li>
      <li>Có thể biên dịch với tốc độ cao lời thoại của mọi người trên nhóm chat</li>
      <li>Có khả năng báo cáo, liên lạc, bàn bạc môt cách tỉ mỉ và chi tiết</li>
      <li>Có kinh nghiệm làm kinh doanh hoặc marketing là một lợi thế, hoặc không có kinh nghiệm nhưng có hứng thú với marketing và kinh doanh (công việc đem lại cơ hội làm marketing và thương lượng với đối tác)</li>
      <li>Có khả năng biên dịch với tốc độ cao tài liệu liên quan đến phát triển dự án phần mềm</li>
      <li>Cần có một trong các chứng chỉ tiếng Anh :
        <ul>
          <li>TOEIC 900+</li>
          <li>TOEFL 97+</li>
          <li>IELTS 6.5+</li>
        </ul>
      </li>
      <li>Cần có chứng chỉ tiếng Nhật : N2+</li>
    </ul>
    <h5>Địa điểm làm việc</h5>
    <ul>
      <li>Hà Nội hoặc Thành phố Hồ Chí Minh</li>
      <li>Trong trường hợp ứng viên có nguyện vọng làm việc tại Thành phố Hồ chí Minh, yêu cầu 3 tháng đầu đi làm tại Hà Nội, rồi sau đó mới chuyển vào Thành phố Hồ Chí Minh. Công ty có dự định thành lập chi nhánh ở Quận 1 nhưng chưa rõ địa điểm và thời gian cụ thể, công ty có trả phí nhà ở và vé máy bay.</li>
    </ul>
    <h5>Chế độ đãi ngộ</h5>
    <ul>
      <li>Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo luật Bảo hiểm</li>
      <li>Xét tăng lương theo năng lực và kết quả công việc: 1 lần/năm.</li>
      <li>Điều chỉnh lương theo trượt giá thị trường: 1 lần/năm.</li>
      <li>Lương tháng 13</li>
      <li>Được hưởng trợ cấp ăn trưa 840.000VND/1 tháng.</li>
      <li>Trợ cấp đi lại tối thiểu 210.000VND/1 tháng, tối đa 630.000 VND/1 tháng (tùy thuộc vào khoảng cách từ nhà đến Công ty)</li>
      <li>Trợ cấp Beauty Care 300.000VND/Tháng với nhân viên nữ ký hợp đồng chính thức</li>
      <li>Trợ cấp thai sản (Hưởng thêm 3 tháng lương của nhân viên ngoài lương do Bảo hiểm và nhà nước chi trả)</li>
      <li>Trợ cấp tiếng Nhật, tiếng Anh, và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...)</li>
      <li>Hỗ trợ phí tham gia Hội thảo ngoài Công ty 100.000 VND/ ngày</li>
      <li>Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, các CLB Game, CLB dạy và học </li>tiếng Nhật, tham gia các bữa tiệc, hoạt động ngoại khóa của công ty ...</li>
      <li>Du lịch hàng năm</li>
      <li>Khám sức khỏe 1 năm/1 lần</li>
    </ul>
    <h5>Lương và Hợp đồng làm việc</h5>
    <ul>
      <li>Mức lương: $400 – $800</li>
      <li>Thử việc 2 tháng</li>
      <li>Sau thử việc, ký hợp đồng chính thức, lương thỏa thuận theo kết quả thử việc</li>
      <li>Ngày nghỉ :
        <ul>
          <li>Nghỉ thứ 7, Chủ Nhật và các ngày lễ do công ty qui định</li>
          <li>Thời gian học tập nghiên cứu : 16 giờ / tháng</li>
        </ul>
      </li>
      <li>Thưởng theo thành tích thực tế từng tháng:
        <ul>
          <li>Quỹ tiền thưởng là 15% lợi nhuận hàng tháng, có thể thay đổi tùy tình hình kinh doanh</li>
          <li>Trả tiền thưởng vào tiền lương tháng tiếp theo</li>
          <li>Tính thưởng từ khi dịch vụ bắt đầu sinh lợi nhuận</li>
        </ul>
      </li>
    </ul>
    <div class="modal-footer"><a class="btn btn-alt btn-primary" href="<%= new_entry_path("entry[m_job_id]" => 7) %>">Apply Now</a></div>
  </div>
</div>